# .github/workflows/reusable-workflow.yml
name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      username:
        description: 'The name of the user'
        required: true
        type: string
      environment:
        description: 'The deployment environment'
        required: true
        type: string
        default: 'production'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: echo "Hello, ${{ inputs.username }}! Deploying to the ${{ inputs.environment }} environment."
